exclude: "^\\.idea"

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.4
    hooks:
      - id: ruff-format
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      # TODO Maybe enable this at some point.
      #- id: no-commit-to-branch
      #  args: ["--branch", "main"]

  - repo: https://github.com/rtts/djhtml
    rev: 3.0.7
    hooks:
      - id: djhtml
        # Indent only HTML files in template directories
        files: .*/templates/.*\.html$

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        files: \.(po|py)$
        args:
          - --license-filepath=.license-header.txt
          - --comment-style=#
          - --detect-license-in-X-top-lines=2
          - --no-extra-eol
          - --allow-past-years # Using these arguments allows for a date range
          - --use-current-year # (original_date - current_date) to be generated.
      - id: insert-license
        files: \.sql$
        args:
          - --license-filepath=.license-header.txt
          - --comment-style=--
          - --detect-license-in-X-top-lines=2
          - --no-extra-eol
          - --allow-past-years # Using these arguments allows for a date range
          - --use-current-year # (original_date - current_date) to be generated.
